/**
 * IPC Events
 * 
 * This file contains all the IPC events used for communication between the main and renderer processes.
 */

export enum IPCEvents {
  // App
  GET_GAME_CONTEXT = 'GET_GAME_CONTEXT',
  FETCH_GAME_CONTEXT = 'FETCH_GAME_CONTEXT',
  APP_READY_TO_SHOW = 'APP_READY_TO_SHOW',
  
  // Window
  OPEN_OPTION_WINDOW = 'OPEN_OPTION_WINDOW',
  FOCUS_CURRENT_WINDOW = 'FOCUS_CURRENT_WINDOW',
  CLOSE_OPTION_WINDOW = 'CLOSE_OPTION_WINDOW',
  SET_AUDIO_MUTE_WINDOW = 'SET_AUDIO_MUTE_WINDOW',
  
  // Multi-account
  SAVE_MASTER_PASSWORD = 'SAVE_MASTER_PASSWORD',
  REMOVE_MASTER_PASSWORD = 'REMOVE_MASTER_PASSWORD',
  CHANGE_MASTER_PASSWORD = 'CHANGE_MASTER_PASSWORD',
  ENCRYPT_CHARACTER_PASSWORD = 'ENCRYPT_CHARACTER_PASSWORD',
  DECRYPT_CHARACTER_PASSWORD = 'DECRYPT_CHARACTER_PASSWORD',
  UNLOCK_APPLICATION = 'UNLOCK_APPLICATION',
  IS_MASTER_PASSWORD_CONFIGURED = 'IS_MASTER_PASSWORD_CONFIGURED',
  SAVE_CHARACTER_IMAGE = 'SAVE_CHARACTER_IMAGE',
  CLOSE_UNLOCK_WINDOW = 'CLOSE_UNLOCK_WINDOW',
  SELECT_TEAM_TO_CONNECT = 'SELECT_TEAM_TO_CONNECT',
  
  // Auto-group
  AUTO_GROUP_PUSH_PATH = 'AUTO_GROUP_PUSH_PATH',
  AUTO_GROUP_SUBSCRIBE_PATH = 'AUTO_GROUP_SUBSCRIBE_PATH',
  
  // Options
  RESET_GAME_DATA = 'RESET_GAME_DATA',
  CLEAR_CACHE = 'CLEAR_CACHE',
  
  // WSA
  CREATE_WSA_WINDOW = 'CREATE_WSA_WINDOW',
  CLOSE_WSA_WINDOW = 'CLOSE_WSA_WINDOW',
  CHECK_WSA_REQUIREMENTS = 'CHECK_WSA_REQUIREMENTS',
} 